# Generated by Django 5.0.3 on 2024-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "crm",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialist", models.CharField(max_length=100)),
                ("specialty", models.CharField(max_length=100)),
                ("user_type", models.CharField(max_length=25)),
                ("gender", models.CharField(max_length=5)),
                ("description", models.TextField()),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "cpf",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("house_number", models.CharField(max_length=5)),
                ("cep", models.CharField(max_length=8)),
                ("birth_date", models.DateTimeField()),
                ("user_type", models.CharField(max_length=25)),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
