# Generated by Django 5.0.3 on 2024-03-12 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_rename_user_cpf_apointment_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("available", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor_crm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.doctor",
                    ),
                ),
            ],
        ),
    ]
