# Generated by Django 5.0.3 on 2024-03-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_doctoravailability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctoravailability",
            name="date",
            field=models.CharField(max_length=100),
        ),
    ]
