# Generated by Django 5.0.3 on 2024-03-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_alter_doctoravailability_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
