# Generated by Django 5.0.3 on 2024-03-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_doctor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="token",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
