# Generated by Django 5.0.3 on 2024-03-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0009_alter_doctor_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="apointment",
            name="specialty",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apointment",
            name="user_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apointment",
            name="date",
            field=models.CharField(max_length=100),
        ),
    ]
