# Generated by Django 5.0.3 on 2024-03-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0010_apointment_specialty_apointment_user_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Apointment",
            new_name="Appointment",
        ),
    ]
